---
development:
  dialect: postgres
  database: {{envOr "MENDOAN_DATABASE_NAME" "mendoan_development"}}
  user: {{envOr "MENDOAN_DATABASE_USER" "mendoan_user"}}
  password: {{envOr "MENDOAN_DATABASE_PASSWORD" "mendoan_password"}}
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "MENDOAN_TEST_DATABASE_URL" "postgres://mendoan_user:mendoan_password@127.0.0.1:5432/mendoan_test?sslmode=disable"}}

production:
  url: {{envOr "MENDOAN_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/mendoan_production?sslmode=disable"}}
